(define (problem run-generator2)
(:domain generator)
(:objects generator - gen tank1 tank2 tank3 tank4 tank5 tank6 tank7 tank8 tank9 - tank)
;(:objects generator - gen tank1 - tank )
(:init
(= ( gen_fuel_level generator) 101)
(= ( capacity generator) 500)
(= (last-used generator) 0)
(= ( tank_fuel_level tank1 ) 100)
(= ( tank_feul_rate_start tank1 ) 0)
(= (tanknum tank1) 1)
(= ( tank_fuel_level tank2 ) 100)
(= ( tank_feul_rate_start tank2 ) 0)
(= (tanknum tank2) 2)
(= ( tank_fuel_level tank3 ) 100)
(= ( tank_feul_rate_start tank3 ) 0)
(= (tanknum tank3) 3)
(= ( tank_fuel_level tank4 ) 100)
(= ( tank_feul_rate_start tank4 ) 0)
(= (tanknum tank4) 4)
(= ( tank_fuel_level tank5 ) 100)
(= ( tank_feul_rate_start tank5 ) 0)
(= (tanknum tank5) 5)
(= ( tank_fuel_level tank6 ) 100)
(= ( tank_feul_rate_start tank6 ) 0)
(= (tanknum tank6) 6)
(= ( tank_fuel_level tank7 ) 100)
(= ( tank_feul_rate_start tank7 ) 0)
(= (tanknum tank7) 7)
(= ( tank_fuel_level tank8 ) 100)
(= ( tank_feul_rate_start tank8 ) 0)
(= (tanknum tank8) 8)
(= ( tank_fuel_level tank9 ) 100)
(= ( tank_feul_rate_start tank9 ) 0)
(= (tanknum tank9) 9)

)
(:goal (generator_ran generator))
;(:metric minimize ( total-time ))
)
