(define (problem run-generator2)
(:domain generator)
(:objects generator - gen tank1 - tank)
;(:objects generator - gen tank1 - tank )
(:init
(= ( gen_fuel_level generator) 901)
(= ( capacity generator) 901)
(= (last-used generator) 0)
(= ( tank_fuel_level tank1 ) 100.1)
(= ( tank_feul_rate_start tank1 ) 0)
(= (tanknum tank1) 1)
)
(:goal (generator_ran generator))
;(:metric minimize ( total-time ))
)
