(define (problem run-generator2)
(:domain generator)
(:objects generator - gen tank1 tank2 - tank)
;(:objects generator - gen tank1 - tank )
(:init
(= ( gen_fuel_level generator) 801)
(= ( capacity generator) 801)
(= (last-used generator) 0)
(= ( tank_fuel_level tank1 ) 100)
(= ( tank_feul_rate_start tank1 ) 0)
(= (tanknum tank1) 1)
(= ( tank_fuel_level tank2 ) 100)
(= ( tank_feul_rate_start tank2 ) 0)
(= (tanknum tank2) 2)
)
(:goal (generator_ran generator))
;(:metric minimize ( total-time ))
)
